project:
  type: website
  output-dir: docs
  
website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About Me"
        menu: 
          - text: "My Resume"
            href: about.qmd
          - text: "Political & Environmental Activism"
            href: active.qmd
      - text: "My Projects" 
        menu: 
        - text: "Environmental Econometrics"
          href: timeseries.qmd          
        - text: "Bayesian Linear Regression"
          href: bayes.qmd
      - text: "Help"
        menu: 
        - text: "Essential Statistical Concepts"
          href: rconcept.qmd
        - text: "Interpretations of Anova"
          href: modelsel.qmd
    sidebar: false
    tools:
      - icon: github
        href: https://github.com/0-cal/my-portfolio
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Owen Callahan"

format:
  html:
    backgroundcolor: "lightgreen"
#   fontcolor: "black"
#   linkcolor: "darkgreen"
#   mainfont: "sarif"
#   max-width: (width of the main text area of the pages)
#   fontsize: (base font size for website)
#   linestretch: (distance between lines of text)
    theme: cosmo
    css: styles.css
    toc: true

editor: source

